### ISSUE TITLE
Transaction history should be combined

### ISSUE THREAD

**Issue by allinfinite** [villagescc/villagescc2.0#31]
1 list of all sent and received transactions, in order.. with option to sort by All | Sent | Received

**Comment by fpSpindola** [comment]
DOne

**Comment by allinfinite** [comment]
The history should be in order by date.
![screen shot 2017-11-24 at 2 55 00 pm](https://user-images.githubusercontent.com/2475429/33226030-81bcf6a2-d127-11e7-8fc5-a4bd4ce42a0c.png)

**Comment by allinfinite** [comment]
Excellent
