### ISSUE TITLE
cycle removal

### ISSUE THREAD

**Issue by themusicgod1** [villagescc/villagescc2.0#36]
something that ripplepay had and villages doesn't - if A, B ,and C have the following balances

A ------| B
B ------| C
C ------| A

what should happen is all 3 balances should be moved as close as possible to 0

A ---|--- B
B ---|--- C
C ---|--- A

in villages we might extend this to first zero untrusted balances, then trusted balances if possible in that order

**Comment by allinfinite** [comment]
I asked Ryan about this. He said that this is taken care of in villages, already during each payment
