### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by allinfinite** [villagescc/villagescc2.0#39]

**Comment by allinfinite** [comment]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108433179-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108433179-1');
</script>
`

**Comment by fpSpindola** [comment]
Done
